# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0002_auto_20170725_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='user_two',
            new_name='friend',
        ),
    ]
